version: "3.9"

networks:
  comic-vine-network:
    name: comic-vine-network
    driver: bridge

services:
  comic-vine-api:
    build: .
    container_name: comic-vine-api
    image: comic-vine-api:latest
    env_file:
      - .env
    environment:
      - TZ=America/Sao_Paulo
    volumes:
      - ${PWD}:/app
    ports:
      - 3000:3000
    depends_on:
      - comic-vine-postgres
      - comic-vine-redis
    networks:
      - comic-vine-network

  comic-vine-postgres:
    image: postgres
    restart: always
    container_name: comic-vine-postgres
    environment:
      - POSTGRES_DB=comic-vine
      - POSTGRES_PASSWORD=7I33rxvqXS5Y
      - TZ=America/Sao_Paulo
    ports:
      - 5432:5432
    networks:
      - comic-vine-network

  comic-vine-redis:
    image: redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - comic-vine-network